# Generated by Django 5.1.15 on 2025-12-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='abierto',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='web',
        ),
    ]

# Generated by Django 5.1.14 on 2025-12-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='abierto',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='web',
        ),
    ]
